name: your_project_name
description: A new Flutter project.

# Your Flutter SDK version
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  uuid: ^4.4.2
  flutter:
    sdk: flutter

  # Other dependencies...
  
flutter:
  uses-material-design: true

  assets:
    - assets/dice-2/
    - assets/icons/
    - assets/w4-s2/
 